#. application.yml
spring:
  application:
    name: eureka-server

  profiles: default
server:
  port: 8010
    
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://192.168.0.3:8010/eureka/
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    
